version: "3.12"

services:
  math:
    build:
      context: .
    container_name: math_agent
    command: python maths.py

  weather:
    build:
      context: .
    container_name: weather_agent
    command: python weather.py

  countstring:
    build:
      context: .
    container_name: countstring_agent
    command: python countstring.py
